name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-python@v2
        with:
          # Once codebase is updated, this can easily be changed to any specific version.
          python-version: "3.8"

      - uses: pre-commit/action@v3.0.0
